site_name: Fliq
site_url: https://oribarilan.github.io/fliq/
repo_url: https://github.com/oribarilan/fliq
repo_name: oribarilan/fliq

theme:
  name: material
  favicon: assets/flick_emoji_2_small.png
  icon:
    repo: fontawesome/brands/github
  logo: assets/flick_emoji_2_small.png
  features:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: deep orange
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: amber

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/oribarilan
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ori-bar-ilan/

plugins:
    - search
    - awesome-pages
    - mkdocstrings:
        handlers:
          python:
            options:
              annotations_path: brief
              show_signature: true
              separate_signature: true
              show_signature_annotations: true
              docstring_style: google
              show_if_no_docstring: false
              show_bases: false
              docstring_section_style: list
              heading_level: 2
              show_source: false

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: 🔗
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: |
  &copy; 2023 <a href="https://github.com/oribarilan"  target="_blank" rel="noopener">Ori Bar-ilan</a>

nav:
    - Welcome to Fliq: index.md
    - Getting Started: getting_started.md
    - Examples: examples.md
    - Reference:
        - API Intro: reference/api_intro.md
        - What's New: reference/release_notes.md
        - Code API:
          - API Index: reference/code_api/api_index.md
          - Mapper Methods: reference/code_api/mapper_methods.md
          - Materializer Methods: reference/code_api/materializer_methods.md
          - Snapshots: reference/code_api/snapshots.md
          - Partitioning: reference/code_api/partitioning.md
          - Peeking: reference/code_api/peeking.md
        - API Roadmap: reference/api_roadmap.md
    - Misc:
        - Performance: misc/performance.md
#    - Contribution:
#        - Contribution: contribution/contribution.md
#        - Development: contribution/development.md